import type { Item } from './types';

export const allItems: Item[] = [
  {
    id: 'p1',
    name: 'Wireless Pro Headphones',
    description: 'Experience immersive sound with our new noise-cancelling headphones.',
    price: 249.99,
    type: 'product',
    category: 'Electronics',
    vendor: 'AudioPhile Inc.',
    rating: 4.8,
    imageId: 'prod1',
    stock: 150,
  },
  {
    id: 'p2',
    name: 'Ergo-Mechanical Keyboard',
    description: 'Type faster and more comfortably with our ergonomic keyboard.',
    price: 129.99,
    type: 'product',
    category: 'Computers & Accessories',
    vendor: 'TechGear',
    rating: 4.9,
    imageId: 'prod2',
    stock: 85,
  },
  {
    id: 'c1',
    name: 'Full-Stack Web Development',
    description: 'Master front-end and back-end technologies to build complete web applications.',
    price: 499.0,
    type: 'course',
    category: 'Courses',
    vendor: 'CodeAcademy',
    rating: 4.7,
    imageId: 'course1',
  },
  {
    id: 'p3',
    name: 'HealthTracker Smartwatch',
    description: 'Monitor your fitness goals and stay connected on the go.',
    price: 199.5,
    type: 'product',
    category: 'Electronics',
    vendor: 'FitBit',
    rating: 4.6,
    imageId: 'prod3',
    stock: 210,
  },
  {
    id: 'c2',
    name: 'Advanced Graphic Design',
    description: 'Unlock your creativity with advanced techniques in branding and illustration.',
    price: 350.0,
    type: 'course',
    category: 'Courses',
    vendor: 'DesignMasters',
    rating: 4.8,
    imageId: 'course2',
  },
  {
    id: 'c3',
    name: 'Data Science with Python',
    description: 'Learn to analyze data, create visualizations, and build predictive models.',
    price: 550.0,
    type: 'course',
    category: 'Courses',
    vendor: 'DataWiz',
    rating: 4.9,
    imageId: 'course3',
  },
];
