import type { Item } from './types';

export const allItems: Item[] = [
  {
    id: 'p1',
    name: 'Wireless Pro Headphones',
    description: 'Experience immersive sound with our new noise-cancelling headphones.',
    price: 249.99,
    type: 'product',
    category: 'Electronics',
    vendor: 'AudioPhile Inc.',
    rating: 4.8,
    imageId: 'prod1',
    stock: 150,
  },
  {
    id: 'p2',
    name: 'Ergo-Mechanical Keyboard',
    description: 'Type faster and more comfortably with our ergonomic keyboard.',
    price: 129.99,
    type: 'product',
    category: 'Computers & Accessories',
    vendor: 'TechGear',
    rating: 4.9,
    imageId: 'prod2',
    stock: 85,
  },
  {
    id: 'c1',
    name: 'Full-Stack Web Development',
    description: 'Master front-end and back-end technologies to build complete web applications. This course covers everything from HTML/CSS to advanced Node.js and React.',
    price: 499.0,
    type: 'course',
    category: 'Courses',
    vendor: 'CodeAcademy',
    rating: 4.7,
    imageId: 'course1',
    lessons: [
      { title: 'Introduction to Web Development', duration: '1 hr', content: 'Get an overview of the web development landscape and the tools you will be using.' },
      { title: 'HTML & CSS Fundamentals', duration: '3 hr', content: 'Learn the building blocks of web pages with HTML and how to style them with CSS.' },
      { title: 'JavaScript for Beginners', duration: '4 hr', content: 'Dive into the most popular programming language for the web.' },
      { title: 'Building with React', duration: '5 hr', content: 'Master the React library to build dynamic user interfaces.' },
      { title: 'Server-side with Node.js & Express', duration: '5 hr', content: 'Learn how to build a robust backend for your applications.' },
      { title: 'Final Project: Build a Full-Stack App', duration: '8 hr', content: 'Apply all your skills to build a complete application from scratch.' },
    ]
  },
  {
    id: 'p3',
    name: 'HealthTracker Smartwatch',
    description: 'Monitor your fitness goals and stay connected on the go.',
    price: 199.5,
    type: 'product',
    category: 'Electronics',
    vendor: 'FitBit',
    rating: 4.6,
    imageId: 'prod3',
    stock: 210,
  },
  {
    id: 'c2',
    name: 'Advanced Graphic Design',
    description: 'Unlock your creativity with advanced techniques in branding and illustration. This course is for designers looking to take their skills to the next level.',
    price: 350.0,
    type: 'course',
    category: 'Courses',
    vendor: 'DesignMasters',
    rating: 4.8,
    imageId: 'course2',
    lessons: [
      { title: 'The Principles of Design', duration: '2 hr', content: 'A refresher on the core principles that make a design work.' },
      { title: 'Advanced Typography', duration: '3 hr', content: 'Learn how to use type as a powerful element in your designs.' },
      { title: 'Brand Identity Design', duration: '4 hr', content: 'Go through the process of creating a complete brand identity for a client.' },
      { title: 'Digital Illustration Techniques', duration: '4 hr', content: 'Explore advanced techniques in Adobe Illustrator and Procreate.' },
      { title: 'Portfolio Project', duration: '6 hr', content: 'Create a stunning piece for your portfolio under expert guidance.' },
    ]
  },
  {
    id: 'c3',
    name: 'Data Science with Python',
    description: 'Learn to analyze data, create visualizations, and build predictive models. This comprehensive course covers Pandas, Matplotlib, and Scikit-learn.',
    price: 550.0,
    type: 'course',
    category: 'Courses',
    vendor: 'DataWiz',
    rating: 4.9,
    imageId: 'course3',
    lessons: [
      { title: 'Python for Data Analysis', duration: '3 hr', content: 'Learn the Python basics needed for data science.' },
      { title: 'Data Manipulation with Pandas', duration: '5 hr', content: 'Become proficient in cleaning, transforming, and analyzing data with Pandas.' },
      { title: 'Data Visualization with Matplotlib & Seaborn', duration: '4 hr', content: 'Create insightful and beautiful data visualizations.' },
      { title: 'Machine Learning with Scikit-learn', duration: '6 hr', content: 'Build your first machine learning models for classification and regression.' },
      { title: 'Capstone Project', duration: '8 hr', content: 'Work on a real-world dataset to solve a business problem.' },
    ]
  },
  {
    id: 'p4',
    name: 'Smart Home Hub',
    description: 'Control all your smart devices from one central hub with voice commands.',
    price: 99.99,
    type: 'product',
    category: 'Home Appliances',
    vendor: 'HomeIO',
    rating: 4.7,
    imageId: 'prod4',
    stock: 300,
  },
  {
    id: 'p5',
    name: 'The Complete JavaScript Guide',
    description: 'A comprehensive book covering everything from fundamentals to advanced JS.',
    price: 45.50,
    type: 'product',
    category: 'Books',
    vendor: 'Publisher Co.',
    rating: 4.9,
    imageId: 'prod5',
    stock: 120,
  },
  {
    id: 'p6',
    name: 'Eco-Friendly Yoga Mat',
    description: 'A non-slip, eco-friendly mat perfect for your daily yoga practice.',
    price: 65.00,
    type: 'product',
    category: 'Sports & Outdoors',
    vendor: 'ZenFlow',
    rating: 4.8,
    imageId: 'prod6',
    stock: 180,
  },
  {
    id: 'p7',
    name: 'Digital Drawing Tablet',
    description: 'Unleash your inner artist with this professional-grade drawing tablet.',
    price: 320.00,
    type: 'product',
    category: 'Computers & Accessories',
    vendor: 'ArtisanTech',
    rating: 4.7,
    imageId: 'prod7',
    stock: 75,
  },
  {
    id: 'c4',
    name: 'Introduction to Digital Marketing',
    description: 'Learn SEO, social media marketing, and content strategy to grow businesses. Perfect for beginners and business owners.',
    price: 299.00,
    type: 'course',
    category: 'Courses',
    vendor: 'MarketProfs',
    rating: 4.6,
    imageId: 'course4',
    lessons: [
      { title: 'Understanding the Digital Marketing Funnel', duration: '1.5 hr', content: 'Learn how customers move from awareness to purchase.' },
      { title: 'Search Engine Optimization (SEO) Basics', duration: '3 hr', content: 'Get your website to rank higher on Google.' },
      { title: 'Social Media Marketing', duration: '3 hr', content: 'Build and engage a community on platforms like Instagram and Facebook.' },
      { title: 'Content Marketing Strategy', duration: '2.5 hr', content: 'Learn to create content that attracts and converts.' },
      { title: 'Email Marketing & Automation', duration: '2 hr', content: 'Build a powerful email list and automate your marketing.' },
    ]
  },
   {
    id: 'p8',
    name: 'Portable Bluetooth Speaker',
    description: 'Take your music anywhere with this compact and powerful speaker.',
    price: 79.99,
    type: 'product',
    category: 'Electronics',
    vendor: 'AudioPhile Inc.',
    rating: 4.7,
    imageId: 'prod8',
    stock: 250,
  },
  {
    id: 'p9',
    name: '4K Action Camera',
    description: 'Capture your adventures in stunning 4K detail with this rugged camera.',
    price: 189.99,
    type: 'product',
    category: 'Electronics',
    vendor: 'Adventure Gear',
    rating: 4.8,
    imageId: 'prod9',
    stock: 120,
  },
  {
    id: 'p10',
    name: 'Gaming Mouse Pro',
    description: 'High-precision gaming mouse with customizable buttons and RGB lighting.',
    price: 89.99,
    type: 'product',
    category: 'Computers & Accessories',
    vendor: 'TechGear',
    rating: 4.8,
    imageId: 'prod10',
    stock: 200,
  },
  {
    id: 'p11',
    name: 'Ultra-Wide Curved Monitor',
    description: 'Immerse yourself in work or play with this stunning 34-inch curved monitor.',
    price: 599.99,
    type: 'product',
    category: 'Computers & Accessories',
    vendor: 'ViewSonic',
    rating: 4.9,
    imageId: 'prod11',
    stock: 60,
  },
  {
    id: 'p12',
    name: 'Espresso Maker Machine',
    description: 'Become your own barista with this professional-grade espresso machine.',
    price: 499.99,
    type: 'product',
    category: 'Home Appliances',
    vendor: 'KitchenPro',
    rating: 4.9,
    imageId: 'prod12',
    stock: 50,
  },
  {
    id: 'p13',
    name: 'Robotic Vacuum Cleaner',
    description: 'Keep your floors spotless with this intelligent, self-charging robotic vacuum.',
    price: 299.00,
    type: 'product',
    category: 'Home Appliances',
    vendor: 'HomeIO',
    rating: 4.7,
    imageId: 'prod13',
    stock: 110,
  },
  {
    id: 'p14',
    name: 'Air Fryer XL',
    description: 'Enjoy your favorite fried foods with up to 80% less fat.',
    price: 119.99,
    type: 'product',
    category: 'Home & Kitchen',
    vendor: 'KitchenPro',
    rating: 4.8,
    imageId: 'prod14',
    stock: 180,
  },
  {
    id: 'p15',
    name: 'Classic Leather Jacket',
    description: 'A timeless and stylish leather jacket made from high-quality materials.',
    price: 289.00,
    type: 'product',
    category: 'Fashion',
    vendor: 'FashionForward',
    rating: 4.9,
    imageId: 'prod15',
    stock: 90,
  },
  {
    id: 'p16',
    name: 'Trail Running Shoes',
    description: 'Durable and comfortable shoes designed for the toughest terrains.',
    price: 139.99,
    type: 'product',
    category: 'Fashion',
    vendor: 'ActiveWear Co.',
    rating: 4.7,
    imageId: 'prod16',
    stock: 150,
  },
  {
    id: 'p17',
    name: 'The Art of Programming',
    description: 'A deep dive into computer science principles and best practices.',
    price: 59.99,
    type: 'product',
    category: 'Books',
    vendor: 'Publisher Co.',
    rating: 4.9,
    imageId: 'prod17',
    stock: 100,
  },
  {
    id: 'c5',
    name: 'Photography Masterclass',
    description: 'From beginner to pro, learn composition, lighting, and editing. This course will teach you how to take stunning photos with any camera.',
    price: 450.00,
    type: 'course',
    category: 'Courses',
    vendor: 'LensMasters',
    rating: 4.9,
    imageId: 'course5',
    lessons: [
      { title: 'Understanding Your Camera', duration: '2 hr', content: 'Learn the fundamentals of shutter speed, aperture, and ISO.' },
      { title: 'Composition and Framing', duration: '3 hr', content: 'Discover the rules of composition to create more compelling images.' },
      { title: 'Lighting Techniques', duration: '3 hr', content: 'Master natural and artificial light to set the mood.' },
      { title: 'Photo Editing with Lightroom', duration: '4 hr', content: 'Learn to edit your photos like a professional.' },
      { title: 'Final Project: Photo Series', duration: '5 hr', content: 'Create a series of photos that tell a story.' },
    ]
  },
  {
    id: 'c6',
    name: 'Personal Finance 101',
    description: 'Master budgeting, saving, and investing for a secure financial future. This course is designed to give you control over your money.',
    price: 199.00,
    type: 'course',
    category: 'Courses',
    vendor: 'WealthWise',
    rating: 4.8,
    imageId: 'course6',
    lessons: [
      { title: 'Creating a Budget That Works', duration: '1.5 hr', content: 'Learn different budgeting methods and find the one that fits your lifestyle.' },
      { title: 'Strategies for Saving', duration: '2 hr', content: 'Discover effective strategies to save money for your goals.' },
      { title: 'Introduction to Investing', duration: '3 hr', content: 'Understand the basics of stocks, bonds, and retirement accounts.' },
      { title: 'Managing Debt', duration: '2 hr', content: 'Learn how to tackle debt and improve your credit score.' },
      { title: 'Building Your Financial Plan', duration: '2.5 hr', content: 'Create a long-term financial plan for your future.' },
    ]
  },
  {
    id: 'c7',
    name: 'Creative Writing Workshop',
    description: 'Learn to write compelling stories, characters, and dialogue. This workshop will help you find your voice and tell your story.',
    price: 250.00,
    type: 'course',
    category: 'Courses',
    vendor: 'StoryCraft',
    rating: 4.7,
    imageId: 'course7',
    lessons: [
      { title: 'Finding Your Story', duration: '2 hr', content: 'Brainstorm ideas and develop a compelling plot.' },
      { title: 'Creating Memorable Characters', duration: '3 hr', content: 'Learn techniques to bring your characters to life.' },
      { title: 'Writing Powerful Dialogue', duration: '2.5 hr', content: 'Craft dialogue that is realistic and moves the story forward.' },
      { title: 'The Art of Revision', duration: '3 hr', content: 'Learn how to revise your work and make it shine.' },
      { title: 'Publishing Your Work', duration: '2 hr', content: 'Get an overview of the publishing industry and how to get your work out there.' },
    ]
  },
  {
    id: 'c8',
    name: 'AI & Machine Learning Foundations',
    description: 'An introduction to the core concepts of AI and machine learning. This course is perfect for those curious about the future of technology.',
    price: 650.00,
    type: 'course',
    category: 'Courses',
    vendor: 'DataWiz',
    rating: 4.9,
    imageId: 'course8',
    lessons: [
      { title: 'What is AI?', duration: '1 hr', content: 'A high-level overview of Artificial Intelligence and its applications.' },
      { title: 'Types of Machine Learning', duration: '2 hr', content: 'Learn about supervised, unsupervised, and reinforcement learning.' },
      { title: 'Your First Neural Network', duration: '4 hr', content: 'Build a simple neural network from scratch using Python.' },
      { title: 'The Ethics of AI', duration: '2 hr', content: 'Discuss the important ethical considerations in AI development.' },
      { title: 'The Future of AI', duration: '1.5 hr', content: 'Explore where AI is heading and its potential impact on society.' },
    ]
  },
   {
    id: 'p18',
    name: 'Drone with 4K Camera',
    description: 'Capture breathtaking aerial footage with this easy-to-fly drone.',
    price: 450.00,
    type: 'product',
    category: 'Electronics',
    vendor: 'Adventure Gear',
    rating: 4.7,
    imageId: 'prod18',
    stock: 65,
  },
  {
    id: 'p19',
    name: 'Noise-Isolating Earbuds',
    description: 'Crystal-clear audio in a compact, comfortable design.',
    price: 119.99,
    type: 'product',
    category: 'Electronics',
    vendor: 'AudioPhile Inc.',
    rating: 4.6,
    imageId: 'prod19',
    stock: 300,
  },
  {
    id: 'p20',
    name: 'Laptop Stand with Cooling Fan',
    description: 'Improve your posture and keep your laptop cool with this adjustable stand.',
    price: 49.99,
    type: 'product',
    category: 'Computers & Accessories',
    vendor: 'TechGear',
    rating: 4.5,
    imageId: 'prod20',
    stock: 400,
  },
  {
    id: 'p21',
    name: 'Smart Coffee Maker',
    description: 'Schedule your brew from your phone and wake up to fresh coffee.',
    price: 89.99,
    type: 'product',
    category: 'Home Appliances',
    vendor: 'KitchenPro',
    rating: 4.6,
    imageId: 'prod21',
    stock: 130,
  },
  {
    id: 'p22',
    name: 'Minimalist Wrist Watch',
    description: 'A sleek and elegant watch for any occasion.',
    price: 159.00,
    type: 'product',
    category: 'Fashion',
    vendor: 'FashionForward',
    rating: 4.8,
    imageId: 'prod22',
    stock: 110,
  },
  {
    id: 'p23',
    name: 'The Pragmatic Programmer',
    description: 'A classic book for any software developer looking to improve their craft.',
    price: 49.95,
    type: 'product',
    category: 'Books',
    vendor: 'Publisher Co.',
    rating: 5.0,
    imageId: 'prod23',
    stock: 80,
  },
  {
    id: 'p24',
    name: 'Science Fiction Anthology',
    description: 'A collection of the best sci-fi short stories from new and classic authors.',
    price: 29.99,
    type: 'product',
    category: 'Books',
    vendor: 'FuturePress',
    rating: 4.7,
    imageId: 'prod24',
    stock: 200,
  },
  {
    id: 'c9',
    name: 'The Art of Public Speaking',
    description: 'Build confidence and captivate any audience with powerful speaking skills. This course will transform the way you communicate.',
    price: 180.00,
    type: 'course',
    category: 'Courses',
    vendor: 'CommunicateCo',
    rating: 4.8,
    imageId: 'course9',
    lessons: [
      { title: 'Overcoming Stage Fright', duration: '1.5 hr', content: 'Learn proven techniques to manage anxiety and speak with confidence.' },
      { title: 'Structuring Your Speech', duration: '2 hr', content: 'Craft a compelling narrative with a clear beginning, middle, and end.' },
      { title: 'Vocal Variety and Body Language', duration: '2.5 hr', content: 'Use your voice and body to engage and persuade your audience.' },
      { title: 'Handling Q&A Sessions', duration: '1.5 hr', content: 'Learn to handle questions with grace and authority.' },
      { title: 'Final Presentation', duration: '2 hr', content: 'Deliver a speech to your peers and receive constructive feedback.' },
    ]
  },
  {
    id: 'p25',
    name: 'Latest Smartphone Model',
    description: 'The latest smartphone with a stunning display and professional-grade camera.',
    price: 1099.00,
    type: 'product',
    category: 'Mobiles & Accessories',
    vendor: 'PhoneCorp',
    rating: 4.9,
    imageId: 'prod25',
    stock: 200,
  },
  {
    id: 'p26',
    name: 'Smart Air Purifier',
    description: 'Breathe cleaner air with our HEPA filter air purifier, controllable via app.',
    price: 189.99,
    type: 'product',
    category: 'Home Appliances',
    vendor: 'HomeIO',
    rating: 4.8,
    imageId: 'prod26',
    stock: 150,
  },
  {
    id: 'p27',
    name: 'Designer Sunglasses',
    description: 'Protect your eyes in style with these designer sunglasses.',
    price: 250.00,
    type: 'product',
    category: 'Fashion',
    vendor: 'FashionForward',
    rating: 4.7,
    imageId: 'prod27',
    stock: 100,
  },
  {
    id: 'p28',
    name: 'Organic Skincare Set',
    description: 'A complete set of organic skincare products for a healthy glow.',
    price: 120.00,
    type: 'product',
    category: 'Beauty & Personal Care',
    vendor: 'GlowUp',
    rating: 4.9,
    imageId: 'prod28',
    stock: 250,
  },
  {
    id: 'p29',
    name: 'Performance Car Tires (Set of 4)',
    description: 'High-performance tires for superior grip and handling in all conditions.',
    price: 800.00,
    type: 'product',
    category: 'Automotive',
    vendor: 'AutoPro',
    rating: 4.8,
    imageId: 'prod29',
    stock: 50,
  },
  {
    id: 'p30',
    name: 'Smartphone Gimbal Stabilizer',
    description: 'Capture smooth, cinematic video with your smartphone.',
    price: 139.99,
    type: 'product',
    category: 'Mobiles & Accessories',
    vendor: 'CinemaGadgets',
    rating: 4.7,
    imageId: 'prod30',
    stock: 120,
  },
  {
    id: 'p31',
    name: 'Wireless Charging Pad',
    description: 'Fast, convenient wireless charging for all your compatible devices.',
    price: 49.99,
    type: 'product',
    category: 'Mobiles & Accessories',
    vendor: 'TechGear',
    rating: 4.6,
    imageId: 'prod31',
    stock: 400,
  },
  {
    id: 'p32',
    name: 'Portable Power Bank 20000mAh',
    description: 'High-capacity power bank to charge your devices on the go.',
    price: 59.99,
    type: 'product',
    category: 'Mobiles & Accessories',
    vendor: 'ChargeUp',
    rating: 4.8,
    imageId: 'prod32',
    stock: 300,
  },
  {
    id: 'p33',
    name: 'Bluetooth Car Adapter',
    description: 'Add Bluetooth connectivity to any car stereo with an AUX input.',
    price: 24.99,
    type: 'product',
    category: 'Mobiles & Accessories',
    vendor: 'AudioPhile Inc.',
    rating: 4.5,
    imageId: 'prod33',
    stock: 500,
  },
  {
    id: 'p34',
    name: 'Professional Chef\'s Knife',
    description: 'A high-carbon stainless steel knife for precision cutting.',
    price: 159.00,
    type: 'product',
    category: 'Home & Kitchen',
    vendor: 'KitchenPro',
    rating: 4.9,
    imageId: 'prod34',
    stock: 150,
  },
  {
    id: 'p35',
    name: 'Non-Stick Cookware Set',
    description: 'A complete 10-piece set of non-stick pots and pans.',
    price: 249.99,
    type: 'product',
    category: 'Home & Kitchen',
    vendor: 'KitchenPro',
    rating: 4.7,
    imageId: 'prod35',
    stock: 100,
  },
  {
    id: 'p36',
    name: 'Electric Kettle',
    description: 'Boil water in minutes with this stylish and fast electric kettle.',
    price: 49.99,
    type: 'product',
    category: 'Home & Kitchen',
    vendor: 'HomeIO',
    rating: 4.6,
    imageId: 'prod36',
    stock: 200,
  },
  {
    id: 'p37',
    name: 'French Press Coffee Maker',
    description: 'Brew rich, flavorful coffee with this classic French press.',
    price: 34.99,
    type: 'product',
    category: 'Home & Kitchen',
    vendor: 'KitchenPro',
    rating: 4.8,
    imageId: 'prod37',
    stock: 250,
  },
  {
    id: 'p38',
    name: 'Organic Face Moisturizer',
    description: 'A lightweight, hydrating moisturizer for all skin types.',
    price: 39.99,
    type: 'product',
    category: 'Beauty & Personal Care',
    vendor: 'GlowUp',
    rating: 4.8,
    imageId: 'prod38',
    stock: 300,
  },
  {
    id: 'p39',
    name: 'Vitamin C Serum',
    description: 'Brighten your skin and reduce fine lines with this powerful serum.',
    price: 45.00,
    type: 'product',
    category: 'Beauty & Personal Care',
    vendor: 'GlowUp',
    rating: 4.9,
    imageId: 'prod39',
    stock: 200,
  },
  {
    id: 'p40',
    name: 'Electric Toothbrush',
    description: 'Achieve a superior clean with this advanced electric toothbrush.',
    price: 129.99,
    type: 'product',
    category: 'Beauty & Personal Care',
    vendor: 'HealthFirst',
    rating: 4.8,
    imageId: 'prod40',
    stock: 150,
  },
  {
    id: 'p41',
    name: 'Natural Deodorant',
    description: 'An effective, aluminum-free deodorant with a fresh scent.',
    price: 14.99,
    type: 'product',
    category: 'Beauty & Personal Care',
    vendor: 'GlowUp',
    rating: 4.5,
    imageId: 'prod41',
    stock: 400,
  },
  {
    id: 'p42',
    name: 'Digital Body Weight Scale',
    description: 'Track your weight and BMI with this accurate smart scale.',
    price: 49.99,
    type: 'product',
    category: 'Health & Household',
    vendor: 'HealthFirst',
    rating: 4.7,
    imageId: 'prod42',
    stock: 200,
  },
  {
    id: 'p43',
    name: 'Resistance Bands Set',
    description: 'A set of 5 resistance bands for a full-body workout at home.',
    price: 29.99,
    type: 'product',
    category: 'Sports & Outdoors',
    vendor: 'ActiveWear Co.',
    rating: 4.6,
    imageId: 'prod43',
    stock: 300,
  },
  {
    id: 'p44',
    name: 'Insulated Water Bottle',
    description: 'Keep your drinks cold for 24 hours or hot for 12 hours.',
    price: 34.99,
    type: 'product',
    category: 'Sports & Outdoors',
    vendor: 'HydratePro',
    rating: 4.8,
    imageId: 'prod44',
    stock: 400,
  },
  {
    id: 'p45',
    name: 'Foam Roller',
    description: 'Relieve muscle soreness and improve recovery with this foam roller.',
    price: 24.99,
    type: 'product',
    category: 'Sports & Outdoors',
    vendor: 'ZenFlow',
    rating: 4.7,
    imageId: 'prod45',
    stock: 250,
  },
  {
    id: 'p46',
    name: 'Adjustable Dumbbells Set',
    description: 'Save space with these adjustable dumbbells, perfect for a home gym.',
    price: 399.99,
    type: 'product',
    category: 'Sports & Outdoors',
    vendor: 'ActiveWear Co.',
    rating: 4.9,
    imageId: 'prod46',
    stock: 50,
  },
  {
    id: 'p47',
    name: 'Dash Cam 1080p',
    description: 'Record your drives for safety and security with this full HD dash cam.',
    price: 79.99,
    type: 'product',
    category: 'Automotive',
    vendor: 'AutoPro',
    rating: 4.6,
    imageId: 'prod47',
    stock: 150,
  },
  {
    id: 'p48',
    name: 'Car Phone Mount',
    description: 'A sturdy and secure phone mount for hands-free navigation.',
    price: 19.99,
    type: 'product',
    category: 'Automotive',
    vendor: 'AutoPro',
    rating: 4.5,
    imageId: 'prod48',
    stock: 400,
  },
  {
    id: 'p49',
    name: 'Portable Tire Inflator',
    description: 'An essential tool for any car owner to handle flat tires.',
    price: 69.99,
    type: 'product',
    category: 'Automotive',
    vendor: 'AutoPro',
    rating: 4.7,
    imageId: 'prod49',
    stock: 200,
  },
  {
    id: 'p50',
    name: 'Water-based Acrylic Paint Set',
    description: 'A vibrant set of 24 acrylic paints for artists of all levels.',
    price: 39.99,
    type: 'product',
    category: 'Art & Crafts',
    vendor: 'ArtisanTech',
    rating: 4.8,
    imageId: 'prod50',
    stock: 200,
  }
];
