import type { Item } from './types';

export const allItems: Item[] = [
  {
    id: 'p1',
    name: 'Wireless Pro Headphones',
    description: 'Experience immersive sound with our new noise-cancelling headphones.',
    price: 249.99,
    type: 'product',
    category: 'Electronics',
    vendor: 'AudioPhile Inc.',
    rating: 4.8,
    imageId: 'prod1',
    stock: 150,
  },
  {
    id: 'p2',
    name: 'Ergo-Mechanical Keyboard',
    description: 'Type faster and more comfortably with our ergonomic keyboard.',
    price: 129.99,
    type: 'product',
    category: 'Computers & Accessories',
    vendor: 'TechGear',
    rating: 4.9,
    imageId: 'prod2',
    stock: 85,
  },
  {
    id: 'c1',
    name: 'Full-Stack Web Development',
    description: 'Master front-end and back-end technologies to build complete web applications.',
    price: 499.0,
    type: 'course',
    category: 'Courses',
    vendor: 'CodeAcademy',
    rating: 4.7,
    imageId: 'course1',
  },
  {
    id: 'p3',
    name: 'HealthTracker Smartwatch',
    description: 'Monitor your fitness goals and stay connected on the go.',
    price: 199.5,
    type: 'product',
    category: 'Electronics',
    vendor: 'FitBit',
    rating: 4.6,
    imageId: 'prod3',
    stock: 210,
  },
  {
    id: 'c2',
    name: 'Advanced Graphic Design',
    description: 'Unlock your creativity with advanced techniques in branding and illustration.',
    price: 350.0,
    type: 'course',
    category: 'Courses',
    vendor: 'DesignMasters',
    rating: 4.8,
    imageId: 'course2',
  },
  {
    id: 'c3',
    name: 'Data Science with Python',
    description: 'Learn to analyze data, create visualizations, and build predictive models.',
    price: 550.0,
    type: 'course',
    category: 'Courses',
    vendor: 'DataWiz',
    rating: 4.9,
    imageId: 'course3',
  },
  {
    id: 'p4',
    name: 'Smart Home Hub',
    description: 'Control all your smart devices from one central hub with voice commands.',
    price: 99.99,
    type: 'product',
    category: 'Electronics',
    vendor: 'HomeIO',
    rating: 4.7,
    imageId: 'prod4',
    stock: 300,
  },
  {
    id: 'p5',
    name: 'The Complete JavaScript Guide',
    description: 'A comprehensive book covering everything from fundamentals to advanced JS.',
    price: 45.50,
    type: 'product',
    category: 'Books',
    vendor: 'Publisher Co.',
    rating: 4.9,
    imageId: 'prod5',
    stock: 120,
  },
  {
    id: 'p6',
    name: 'Eco-Friendly Yoga Mat',
    description: 'A non-slip, eco-friendly mat perfect for your daily yoga practice.',
    price: 65.00,
    type: 'product',
    category: 'Sports & Outdoors',
    vendor: 'ZenFlow',
    rating: 4.8,
    imageId: 'prod6',
    stock: 180,
  },
  {
    id: 'p7',
    name: 'Digital Drawing Tablet',
    description: 'Unleash your inner artist with this professional-grade drawing tablet.',
    price: 320.00,
    type: 'product',
    category: 'Computers & Accessories',
    vendor: 'ArtisanTech',
    rating: 4.7,
    imageId: 'prod7',
    stock: 75,
  },
  {
    id: 'c4',
    name: 'Introduction to Digital Marketing',
    description: 'Learn SEO, social media marketing, and content strategy to grow businesses.',
    price: 299.00,
    type: 'course',
    category: 'Courses',
    vendor: 'MarketProfs',
    rating: 4.6,
    imageId: 'course4',
  },
   {
    id: 'p8',
    name: 'Portable Bluetooth Speaker',
    description: 'Take your music anywhere with this compact and powerful speaker.',
    price: 79.99,
    type: 'product',
    category: 'Electronics',
    vendor: 'AudioPhile Inc.',
    rating: 4.7,
    imageId: 'prod8',
    stock: 250,
  },
  {
    id: 'p9',
    name: '4K Action Camera',
    description: 'Capture your adventures in stunning 4K detail with this rugged camera.',
    price: 189.99,
    type: 'product',
    category: 'Electronics',
    vendor: 'Adventure Gear',
    rating: 4.8,
    imageId: 'prod9',
    stock: 120,
  },
  {
    id: 'p10',
    name: 'Gaming Mouse Pro',
    description: 'High-precision gaming mouse with customizable buttons and RGB lighting.',
    price: 89.99,
    type: 'product',
    category: 'Computers & Accessories',
    vendor: 'TechGear',
    rating: 4.8,
    imageId: 'prod10',
    stock: 200,
  },
  {
    id: 'p11',
    name: 'Ultra-Wide Curved Monitor',
    description: 'Immerse yourself in work or play with this stunning 34-inch curved monitor.',
    price: 599.99,
    type: 'product',
    category: 'Computers & Accessories',
    vendor: 'ViewSonic',
    rating: 4.9,
    imageId: 'prod11',
    stock: 60,
  },
  {
    id: 'p12',
    name: 'Espresso Maker Machine',
    description: 'Become your own barista with this professional-grade espresso machine.',
    price: 499.99,
    type: 'product',
    category: 'Home & Kitchen',
    vendor: 'KitchenPro',
    rating: 4.9,
    imageId: 'prod12',
    stock: 50,
  },
  {
    id: 'p13',
    name: 'Robotic Vacuum Cleaner',
    description: 'Keep your floors spotless with this intelligent, self-charging robotic vacuum.',
    price: 299.00,
    type: 'product',
    category: 'Home & Kitchen',
    vendor: 'HomeIO',
    rating: 4.7,
    imageId: 'prod13',
    stock: 110,
  },
  {
    id: 'p14',
    name: 'Air Fryer XL',
    description: 'Enjoy your favorite fried foods with up to 80% less fat.',
    price: 119.99,
    type: 'product',
    category: 'Home & Kitchen',
    vendor: 'KitchenPro',
    rating: 4.8,
    imageId: 'prod14',
    stock: 180,
  },
  {
    id: 'p15',
    name: 'Classic Leather Jacket',
    description: 'A timeless and stylish leather jacket made from high-quality materials.',
    price: 289.00,
    type: 'product',
    category: 'Clothing, Shoes & Jewelry',
    vendor: 'FashionForward',
    rating: 4.9,
    imageId: 'prod15',
    stock: 90,
  },
  {
    id: 'p16',
    name: 'Trail Running Shoes',
    description: 'Durable and comfortable shoes designed for the toughest terrains.',
    price: 139.99,
    type: 'product',
    category: 'Clothing, Shoes & Jewelry',
    vendor: 'ActiveWear Co.',
    rating: 4.7,
    imageId: 'prod16',
    stock: 150,
  },
  {
    id: 'p17',
    name: 'The Art of Programming',
    description: 'A deep dive into computer science principles and best practices.',
    price: 59.99,
    type: 'product',
    category: 'Books',
    vendor: 'Publisher Co.',
    rating: 4.9,
    imageId: 'prod17',
    stock: 100,
  },
  {
    id: 'c5',
    name: 'Photography Masterclass',
    description: 'From beginner to pro, learn composition, lighting, and editing.',
    price: 450.00,
    type: 'course',
    category: 'Courses',
    vendor: 'LensMasters',
    rating: 4.9,
    imageId: 'course5',
  },
  {
    id: 'c6',
    name: 'Personal Finance 101',
    description: 'Master budgeting, saving, and investing for a secure financial future.',
    price: 199.00,
    type: 'course',
    category: 'Courses',
    vendor: 'WealthWise',
    rating: 4.8,
    imageId: 'course6',
  },
  {
    id: 'c7',
    name: 'Creative Writing Workshop',
    description: 'Learn to write compelling stories, characters, and dialogue.',
    price: 250.00,
    type: 'course',
    category: 'Courses',
    vendor: 'StoryCraft',
    rating: 4.7,
    imageId: 'course7',
  },
  {
    id: 'c8',
    name: 'AI & Machine Learning Foundations',
    description: 'An introduction to the core concepts of AI and machine learning.',
    price: 650.00,
    type: 'course',
    category: 'Courses',
    vendor: 'DataWiz',
    rating: 4.9,
    imageId: 'course8',
  },
   {
    id: 'p18',
    name: 'Drone with 4K Camera',
    description: 'Capture breathtaking aerial footage with this easy-to-fly drone.',
    price: 450.00,
    type: 'product',
    category: 'Electronics',
    vendor: 'Adventure Gear',
    rating: 4.7,
    imageId: 'prod18',
    stock: 65,
  },
  {
    id: 'p19',
    name: 'Noise-Isolating Earbuds',
    description: 'Crystal-clear audio in a compact, comfortable design.',
    price: 119.99,
    type: 'product',
    category: 'Electronics',
    vendor: 'AudioPhile Inc.',
    rating: 4.6,
    imageId: 'prod19',
    stock: 300,
  },
  {
    id: 'p20',
    name: 'Laptop Stand with Cooling Fan',
    description: 'Improve your posture and keep your laptop cool with this adjustable stand.',
    price: 49.99,
    type: 'product',
    category: 'Computers & Accessories',
    vendor: 'TechGear',
    rating: 4.5,
    imageId: 'prod20',
    stock: 400,
  },
  {
    id: 'p21',
    name: 'Smart Coffee Maker',
    description: 'Schedule your brew from your phone and wake up to fresh coffee.',
    price: 89.99,
    type: 'product',
    category: 'Home & Kitchen',
    vendor: 'KitchenPro',
    rating: 4.6,
    imageId: 'prod21',
    stock: 130,
  },
  {
    id: 'p22',
    name: 'Minimalist Wrist Watch',
    description: 'A sleek and elegant watch for any occasion.',
    price: 159.00,
    type: 'product',
    category: 'Clothing, Shoes & Jewelry',
    vendor: 'FashionForward',
    rating: 4.8,
    imageId: 'prod22',
    stock: 110,
  },
  {
    id: 'p23',
    name: 'The Pragmatic Programmer',
    description: 'A classic book for any software developer looking to improve their craft.',
    price: 49.95,
    type: 'product',
    category: 'Books',
    vendor: 'Publisher Co.',
    rating: 5.0,
    imageId: 'prod23',
    stock: 80,
  },
  {
    id: 'p24',
    name: 'Science Fiction Anthology',
    description: 'A collection of the best sci-fi short stories from new and classic authors.',
    price: 29.99,
    type: 'product',
    category: 'Books',
    vendor: 'FuturePress',
    rating: 4.7,
    imageId: 'prod24',
    stock: 200,
  },
  {
    id: 'c9',
    name: 'The Art of Public Speaking',
    description: 'Build confidence and captivate any audience with powerful speaking skills.',
    price: 180.00,
    type: 'course',
    category: 'Courses',
    vendor: 'CommunicateCo',
    rating: 4.8,
    imageId: 'course9',
  }
];
